apiVersion: v1
kind: ConfigMap
metadata:
  name: fiocfg
  namespace: portworx
data:
  fiojobs.fio: |-
    [global]
    ioengine=libaio
    size=1GiB
    name=test
    direct=1
    iodepth=128
    stonewall
    filename=/data/fio.dat
    buffer_compress_percentage=50
    end_fsync=1
    ##----Begin 4k tests-------
    [4k-write]
    blocksize=4k
    readwrite=write
    [4k-read]
    blocksize=4k
    readwrite=read
    [4k-rand-write]
    blocksize=4k
    readwrite=randwrite
    [4k-rand-read]
    blocksize=4k
    readwrite=randread
    [4k-mix-rand-50-50]
    blocksize=4k
    readwrite=randrw
    rwmixread=50
    [4k-mix-rand-80-20]
    blocksize=4k
    readwrite=randrw
    rwmixread=80
    [4k-mix-rand-20-80]
    blocksize=4k
    readwrite=randrw
    rwmixread=20
    ##----Begin 16k tests-------
    [16k-write]
    blocksize=16k
    readwrite=write
    [16k-read]
    blocksize=16k
    readwrite=read
    [16k-rand-write]
    blocksize=16k
    readwrite=randwrite
    [16k-rand-read]
    blocksize=16k
    readwrite=randread
    [16k-mix-rand-50-50]
    blocksize=16k
    readwrite=randrw
    rwmixread=50
    [16k-mix-rand-80-20]
    blocksize=16k
    readwrite=randrw
    rwmixread=80
    [16k-mix-rand-20-80]
    blocksize=16k
    readwrite=randrw
    rwmixread=20
    ##----Begin 64k tests-------
    [64k-write]
    blocksize=64k
    readwrite=write
    [64k-read]
    blocksize=64k
    readwrite=read
    [64k-rand-write]
    blocksize=64k
    readwrite=randwrite
    [64k-rand-read]
    blocksize=64k
    readwrite=randread
    [64k-mix-rand-50-50]
    blocksize=64k
    readwrite=randrw
    rwmixread=50
    [64k-mix-rand-80-20]
    blocksize=64k
    readwrite=randrw
    rwmixread=80
    [64k-mix-rand-20-80]
    blocksize=64k
    readwrite=randrw
    rwmixread=20
    ##----Begin 256k tests-------
    [256k-write]
    blocksize=256k
    readwrite=write
    [256k-read]
    blocksize=256k
    readwrite=read
    [256k-rand-write]
    blocksize=256k
    readwrite=randwrite
    [256k-rand-read]
    blocksize=256k
    readwrite=randread
    [256k-mix-rand-50-50]
    blocksize=256k
    readwrite=randrw
    rwmixread=50
    [256k-mix-rand-80-20]
    blocksize=256k
    readwrite=randrw
    rwmixread=80
    [256k-mix-rand-20-80]
    blocksize=256k
    readwrite=randrw
    rwmixread=20

